name = "TransformedLogDensities"
uuid = "f9bc47f6-f3f8-4f3b-ab21-f8bc73906f26"
authors = ["Tamás K. Papp <tkpapp@gmail.com>"]
version = "1.1.1"

[deps]
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"

[compat]
LogDensityProblems = "1, 2"
TransformVariables = "0.6, 0.7, 0.8, 0.9, 1"
julia = "1.10"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LogDensityProblemsAD = "996a588d-648d-4e1f-a8f0-a84b347e47b1"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Distributions", "ForwardDiff", "Test", "LogDensityProblemsAD"]
